import {InventoryItem, StockMovement} from "./features/dashboard/types";

export const INITIAL_INVENTORY: InventoryItem[] = [
    {
        id: 'inv1',
        sku: 'GLS-TMP-12MM',
        name: '12mm Clear Tempered Architectural Glass Sheet (2.4m x 1.8m)',
        category: 'Structural Glass',
        warehouse: 'Colombo Central Hub',
        quantityOnHand: 48,
        reserved: 18,
        freeToUse: 30,
        minThreshold: 15,
        unitCost: 28000,
        unitPrice: 45000,
        unit: 'Sheets',
        status: 'in_stock',
        lastRestocked: '2026-09-10'
    },
    {
        id: 'inv2',
        sku: 'HNG-HD-001',
        name: 'Heavy-Duty Floor Spring Hydraulic Hinge Set (300kg Load)',
        category: 'Hardware & Fittings',
        warehouse: 'Colombo Central Hub',
        quantityOnHand: 14,
        reserved: 4,
        freeToUse: 10,
        minThreshold: 8,
        unitCost: 5200,
        unitPrice: 8500,
        unit: 'Sets',
        status: 'in_stock',
        lastRestocked: '2026-09-15'
    },
    {
        id: 'inv3',
        sku: 'TEL-RCK-24U',
        name: 'Weatherproof Outdoor Telecom Rack Enclosure (24U IP65)',
        category: 'Telecom Hardware',
        warehouse: 'Negombo Depot',
        quantityOnHand: 6,
        reserved: 4,
        freeToUse: 2,
        minThreshold: 5,
        unitCost: 42000,
        unitPrice: 65000,
        unit: 'Units',
        status: 'low_stock',
        lastRestocked: '2026-08-28'
    },
    {
        id: 'inv4',
        sku: 'ALU-PRF-BLK',
        name: 'Anodized Black Aluminum Extrusion Profile (6m Bar)',
        category: 'Aluminum Fabrication',
        warehouse: 'Colombo Central Hub',
        quantityOnHand: 120,
        reserved: 40,
        freeToUse: 80,
        minThreshold: 30,
        unitCost: 7800,
        unitPrice: 12500,
        unit: 'Bars',
        status: 'in_stock',
        lastRestocked: '2026-09-18'
    },
    {
        id: 'inv5',
        sku: 'SPG-SS316-M',
        name: 'Marine-Grade Stainless Steel 316 Balustrade Spigot Clamp',
        category: 'Hardware & Fittings',
        warehouse: 'Colombo Central Hub',
        quantityOnHand: 72,
        reserved: 36,
        freeToUse: 36,
        minThreshold: 50,
        unitCost: 3900,
        unitPrice: 6500,
        unit: 'Pieces',
        status: 'low_stock',
        lastRestocked: '2026-09-02'
    },
    {
        id: 'inv6',
        sku: 'SRG-PRO-20K',
        name: 'Surge Protection Lightning Arrester Junction Unit (20kA)',
        category: 'Telecom Hardware',
        warehouse: 'Negombo Depot',
        quantityOnHand: 3,
        reserved: 3,
        freeToUse: 0,
        minThreshold: 10,
        unitCost: 3100,
        unitPrice: 5000,
        unit: 'Units',
        status: 'out_of_stock',
        lastRestocked: '2026-08-14'
    },
    {
        id: 'inv7',
        sku: 'SNS-OPT-SLD',
        name: 'Infrared Motion & Presence Dual Safety Activation Sensor',
        category: 'Automation Sensors',
        warehouse: 'Mobile Van Unit 4',
        quantityOnHand: 8,
        reserved: 2,
        freeToUse: 6,
        minThreshold: 4,
        unitCost: 26000,
        unitPrice: 40000,
        unit: 'Units',
        status: 'in_stock',
        lastRestocked: '2026-09-12'
    }
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
    {
        id: 'm1',
        ref: 'WH/IN/0024',
        date: '2026-09-22 11:30',
        itemName: 'Heavy-Duty Floor Spring Hydraulic Hinge Set',
        sku: 'HNG-HD-001',
        fromLocation: 'Supplier: Dorma Fab Asia',
        toLocation: 'Colombo Central Hub - Shelf B2',
        quantity: 10,
        type: 'receipt',
        status: 'completed',
        operator: 'Tharindu Silva'
    },
    {
        id: 'm2',
        ref: 'WH/OUT/0089',
        date: '2026-09-22 09:15',
        itemName: 'Heavy Duty Glass Door Pivot Hinge Replacement',
        sku: 'HNG-HD-001',
        fromLocation: 'Colombo Central Hub',
        toLocation: 'Customer: Cinnamon Hotels (Hikka Trance)',
        quantity: 2,
        type: 'delivery',
        status: 'completed',
        operator: 'Kenneth Kumarasinghe'
    },
    {
        id: 'm3',
        ref: 'WH/INT/0015',
        date: '2026-09-21 16:40',
        itemName: 'Infrared Motion & Presence Dual Safety Activation Sensor',
        sku: 'SNS-OPT-SLD',
        fromLocation: 'Colombo Central Hub',
        toLocation: 'Mobile Van Unit 4',
        quantity: 4,
        type: 'internal',
        status: 'completed',
        operator: 'Sandun Perera'
    },
    {
        id: 'm4',
        ref: 'WH/IN/0023',
        date: '2026-09-18 14:00',
        itemName: 'Anodized Black Aluminum Extrusion Profile',
        sku: 'ALU-PRF-BLK',
        fromLocation: 'Supplier: Alumex Lanka PLC',
        toLocation: 'Colombo Central Hub - Yard A',
        quantity: 60,
        type: 'receipt',
        status: 'completed',
        operator: 'Tharindu Silva'
    }
];